(()=>{
'use strict';
const $=s=>document.querySelector(s);let sb=null,session=null,user=null;
const authGate=$('#authGate'),labApp=$('#labApp'),authMsg=$('#authMsg'),googleBtn=$('#googleAdminBtn'),magicBtn=$('#magicLinkBtn'),bootstrapBox=$('#bootstrapBox'),claimBtn=$('#claimAdminBtn'),signOut=$('#signOutBtn');
const say=(el,msg,bad=false)=>{if(!el)return;el.textContent=msg;el.style.color=bad?'#b84837':'#57534b'};
async function init(){
  try{const cfg=await fetch('/api/config',{cache:'no-store'}).then(r=>r.json());if(!cfg.supabaseUrl||!cfg.supabasePublishableKey)throw new Error('Supabase is not connected.');sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);const x=await sb.auth.getSession();session=x.data.session;user=session?.user||null;if(!user)return showSignedOut();await checkRole();}
  catch(e){say(authMsg,e.message,true)}
}
function showSignedOut(){authGate.hidden=false;labApp.hidden=true;bootstrapBox.hidden=true;signOut.hidden=true;googleBtn.hidden=false;say(authMsg,'Sign in with the admin account to open EMET LAB.');}
async function checkRole(){const {data,error}=await sb.from('profiles').select('id,email,role').eq('id',user.id).maybeSingle();if(error)throw error;if(data?.role==='admin'){authGate.hidden=true;labApp.hidden=false;signOut.hidden=false;await refresh();return}authGate.hidden=false;labApp.hidden=true;googleBtn.hidden=true;bootstrapBox.hidden=false;signOut.hidden=false;say(authMsg,`Signed in as ${user.email}. This account is not an admin yet.`)}
googleBtn?.addEventListener('click',async()=>{try{const {error}=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+'/admin-lab.html'}});if(error)throw error}catch(e){say(authMsg,e.message,true)}});
magicBtn?.addEventListener('click',async()=>{const email=$('#adminEmail')?.value.trim();if(!email)return say(authMsg,'Enter the admin email first.',true);magicBtn.disabled=true;try{const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+'/admin-lab.html'}});if(error)throw error;say(authMsg,`Magic link sent to ${email}. Open it on this device to continue.`)}catch(e){say(authMsg,e.message,true)}finally{magicBtn.disabled=false}});
signOut?.addEventListener('click',async()=>{await sb.auth.signOut();location.reload()});
claimBtn?.addEventListener('click',async()=>{const token=$('#bootstrapToken').value.trim();if(!token)return say(authMsg,'Enter the one time bootstrap code.',true);claimBtn.disabled=true;try{const {data,error}=await sb.rpc('claim_first_admin',{p_token:token});if(error)throw error;if(!data)throw new Error('The bootstrap code is invalid or has already been used.');await checkRole()}catch(e){say(authMsg,e.message,true)}finally{claimBtn.disabled=false}});
function featureVector(r){const a=r.aiAnalysis||{},m=a.assessment?.authorshipMap||{},p=a.assessment?.process||{},pan=a.local?.ensemble?.panels||a.diagnostics?.panels||{},f=a.fingerprintLab||{};return{processScore:+(p.score||0),documentSignalScore:+(m.documentSignalScore||0),rhythm:+(pan.rhythm||0),lexical:+(pan.lexical||0),discourse:+(pan.discourse||0),surfaceStyle:+(pan.surfaceStyle||0),predictability:+(pan.predictability||0),aiResidue:+(pan.aiResidue||0),fingerprintCoverage:+(f.runSessionTraceCoverage||0),rsidCount:+(a.local?.fileForensics?.rsidCount||0),trackedChanges:+(a.local?.fileForensics?.trackedRevisionMarkers||0),metadataLifetimeMinutes:+(a.local?.fileForensics?.metadataLifetimeMinutes||0),zipUniqueTimes:+(a.local?.fileForensics?.zipUniqueTimes||0)}}
async function sha256(file){const b=await file.arrayBuffer(),d=await crypto.subtle.digest('SHA-256',b);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
$('#experimentForm')?.addEventListener('submit',async e=>{e.preventDefault();const file=$('#experimentFile').files[0],msg=$('#experimentMsg'),btn=$('#experimentBtn');if(!file)return;btn.disabled=true;say(msg,'Scanning the file with the production engine…');try{const fd=new FormData();fd.append('file',file,file.name);const rr=await fetch('/api/analyze',{method:'POST',body:fd});const result=await rr.json();if(!rr.ok)throw new Error(result.error||result.detail||'Scan failed');const hash=await sha256(file),label=$('#experimentLabel').value,language=$('#experimentLanguage').value,domain=$('#experimentDomain').value.trim()||'general',notes=$('#experimentNotes').value.trim(),vector=featureVector(result);const {error:gErr}=await sb.from('ground_truth_documents').upsert({file_sha256:hash,label,language,source_note:notes||`Admin controlled experiment: ${file.name}`},{onConflict:'file_sha256'});if(gErr)throw gErr;const {error:cErr}=await sb.from('training_candidates').insert({asset_sha256:hash,language,domain,source_type:'admin_experiment',proposed_label:label,trust_tier:3,feature_schema_version:'emet-v1',features:{vector,filename:file.name,size:file.size,engine:result.aiAnalysis?.version||null,process:result.aiAnalysis?.assessment?.process||null,authorshipMapSummary:result.aiAnalysis?.assessment?.authorshipMap?{documentSignalScore:result.aiAnalysis.assessment.authorshipMap.documentSignalScore,estimatedAIShare:result.aiAnalysis.assessment.authorshipMap.estimatedAIShare}:null},notes,review_status:'approved',reviewed_by:user.id,reviewed_at:new Date().toISOString(),created_by:user.id});if(cErr)throw cErr;say(msg,`Added as Tier 3 ground truth. SHA-256 ${hash.slice(0,12)}…`);e.target.reset();$('#experimentDomain').value='academic';await refresh()}catch(err){say(msg,err.message,true)}finally{btn.disabled=false}});
async function refresh(){await Promise.all([loadStats(),loadCandidates(),loadRuns(),loadModels()])}
async function loadStats(){const [p,a,r,m]=await Promise.all([sb.from('training_candidates').select('id',{count:'exact',head:true}).eq('review_status','pending'),sb.from('training_candidates').select('id',{count:'exact',head:true}).eq('review_status','approved'),sb.from('training_runs').select('id',{count:'exact',head:true}),sb.from('model_registry').select('id',{count:'exact',head:true}).eq('status','active')]);$('#statPending').textContent=p.count||0;$('#statApproved').textContent=a.count||0;$('#statRuns').textContent=r.count||0;$('#statModels').textContent=m.count||0}
async function loadCandidates(){const {data,error}=await sb.from('training_candidates').select('*').order('created_at',{ascending:false}).limit(30);const box=$('#candidateList');if(error){box.textContent=error.message;return}box.innerHTML=(data||[]).map(x=>`<article class="candidate"><div><div class="candidateMeta"><span>TIER ${x.trust_tier}</span><span>${esc(x.source_type)}</span><span>${esc(x.language||'')}</span><span>${esc(x.domain||'')}</span><span>${esc(x.review_status)}</span></div><strong>${esc(x.proposed_label)}</strong><p>${esc(x.notes||x.asset_sha256)}</p></div><div class="candidateActions">${x.review_status==='pending'?`<button class="approve" data-action="approve" data-id="${x.id}">Approve</button><button data-action="reject" data-id="${x.id}">Reject</button>`:''}</div></article>`).join('')||'<p class="labHint">No candidates yet.</p>'}
$('#candidateList')?.addEventListener('click',async e=>{const b=e.target.closest('button[data-action]');if(!b)return;b.disabled=true;const status=b.dataset.action==='approve'?'approved':'rejected';const {error}=await sb.from('training_candidates').update({review_status:status,reviewed_by:user.id,reviewed_at:new Date().toISOString()}).eq('id',b.dataset.id);if(error)alert(error.message);await refresh()});
async function loadRuns(){const {data}=await sb.from('training_runs').select('*').order('created_at',{ascending:false}).limit(12);$('#runsList').innerHTML=(data||[]).map(x=>`<div class="miniItem"><div><b>${esc(x.candidate_version)}</b><br><small>${esc(x.language)} · ${esc(x.domain)} · ${fmt(x.created_at)}</small></div><span class="status ${esc(x.status)}">${esc(x.status)}</span></div>`).join('')||'<p class="labHint">No training runs yet.</p>'}
async function loadModels(){const {data}=await sb.from('model_registry').select('*').order('created_at',{ascending:false}).limit(12);$('#modelsList').innerHTML=(data||[]).map(x=>`<div class="miniItem"><div><b>${esc(x.version)}</b><br><small>${esc(x.language)} · ${esc(x.domain)} · test BA ${Number(x.metrics?.test?.balancedAccuracy||0).toFixed(3)}</small></div><div>${x.status==='shadow'?`<button class="labGhost promoteBtn" data-version="${esc(x.version)}">Promote</button>`:`<span class="status ${esc(x.status)}">${esc(x.status)}</span>`}</div></div>`).join('')||'<p class="labHint">No models yet.</p>'}
$('#queueRunBtn')?.addEventListener('click',async()=>{const b=$('#queueRunBtn');b.disabled=true;b.textContent='Training…';try{const r=await fetch('/api/admin/train',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${session.access_token}`},body:JSON.stringify({language:'he',domain:'academic'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Training failed');alert(`Shadow model ${d.version} created. Holdout balanced accuracy: ${d.metrics.test.balancedAccuracy}`);await refresh()}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent='Queue Hebrew text run'}});
$('#modelsList')?.addEventListener('click',async e=>{const b=e.target.closest('.promoteBtn');if(!b)return;if(!confirm(`Promote ${b.dataset.version} to production?`))return;b.disabled=true;try{const r=await fetch('/api/admin/promote',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${session.access_token}`},body:JSON.stringify({version:b.dataset.version})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Promotion failed');await refresh()}catch(err){alert(err.message)}finally{b.disabled=false}});
$('#refreshBtn')?.addEventListener('click',refresh);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));const fmt=s=>s?new Date(s).toLocaleString():'—';
init();
})();