(()=>{
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=v=>v===null||v===undefined||v===''?'Not available':typeof v==='number'?String(Math.round(v*1000)/1000):String(v);
  const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,Math.round(Number(n)||0)));
  const txt=v=>JSON.stringify(v||{}).toLowerCase();
  const meter=(label,value,help)=>{const n=clamp(value);return `<div class="mmMeter"><div><b>${esc(label)}</b><span>${esc(help||'')}</span></div><strong>${n}</strong><i><u style="width:${n}%"></u></i></div>`};
  const kv=rows=>`<div class="mmKv">${rows.filter(([,v])=>v!==null&&v!==undefined&&v!=='').map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(fmt(v))}</b></div>`).join('')}</div>`;
  function layer(label,score,weight,available=true,detail='',kind='signal'){return{label,score:clamp(score),weight:Number(weight)||0,available:Boolean(available),detail,kind}}
  function weighted(layers,prior=40){const a=layers.filter(x=>x.available&&x.weight>0&&x.kind!=='counter');if(!a.length)return clamp(prior,1,99);let sw=0,s=0;for(const x of a){sw+=x.weight;s+=x.score*x.weight}let raw=s/sw;for(const x of layers.filter(x=>x.available&&x.kind==='counter'))raw-=x.score*x.weight;return clamp(raw,1,99)}
  function proofState(data,m){
    const gt=data?.groundTruth,prov=data?.aiAnalysis?.assessment?.provenance||data?.aiAnalysis?.provenance||{},deep=m?.deepContainer||data?.deepForensics||{},markers=deep?.container?.generatorMarkers||m?.metadata?.generatorFingerprints||[];
    if(gt?.matched)return{verified:true,score:100,label:'Exact known ground truth',why:'Exact SHA-256 identity matched a labeled reference file.'};
    if(prov?.status==='authenticated_source_claim')return{verified:true,score:100,label:'Authenticated provenance',why:'A validated provenance claim directly attributes the source.'};
    if(markers.length)return{verified:false,score:98,label:'Direct generator marker',why:`The original container names ${markers.join(', ')}. This is strong attribution evidence, but editable metadata is not treated as cryptographic proof.`};
    return{verified:false,score:null,label:'Evidence estimate',why:'No exact identity or authenticated source claim is retained in this file.'};
  }
  function visionLayers(m){
    const vf=m?.visionFusion||{},o=vf.aiOriginEstimate||{},signals=Array.isArray(o.signals)?o.signals:[];
    const map={
      provenance_generator:'Generator / provenance',global_generative_prior:'Global generative fingerprint',existing_local_forensics:'Pixel forensic ensemble',regional_inconsistency:'Regional inconsistency',boundary_adhesion:'Edit boundary adhesion',recompression:'Recompression analysis',copy_move:'Copy move screen',camera_counterevidence:'Camera capture evidence',container_generator_marker:'Container generator marker'
    };
    return signals.map(s=>layer(map[s.id]||String(s.id||'signal').replaceAll('_',' '),s.score,Math.max(.2,Number(s.weight)||.5),true,s.markers?.join(', ')||`${s.kind||'signal'} layer`,s.kind==='counter'?'counter':'signal'));
  }
  function fallbackImageLayers(m){
    const p=m.pixelForensics||{},r=m.recompression||{},c=m.copyMove||{},s=m.syntheticImageSignal||{},meta=m.metadata||{},gens=meta.generatorFingerprints||[],all=txt(meta),camera=/iphone|samsung|pixel|canon|nikon|sony|fujifilm|olympus|panasonic|leica|huawei|xiaomi/.test(all),l=[];
    l.push(layer('Generator fingerprint',gens.length?99:18,3,true,gens.length?gens.join(', '):'No exposed generator name'));
    l.push(layer('Pixel forensic fusion',Math.max(8,Number(s.score)||0),2,true,'Local pixel and metadata analysis'));
    l.push(layer('Noise residual',p.noiseResidual<1.8&&p.edgeEnergy>8?78:p.noiseResidual<3?58:34,1.2,p.noiseResidual!=null,`noise ${p.noiseResidual??'n/a'} / edge ${p.edgeEnergy??'n/a'}`));
    l.push(layer('Texture entropy',p.entropy>7.7?42:p.entropy<5.2?63:48,.7,p.entropy!=null,`entropy ${p.entropy??'n/a'}`));
    l.push(layer('JPEG recompression',r.supported?Math.max(15,Number(r.recompressionAnomalyScore)||0):45,.8,!!r.supported,r.supported?`score ${r.recompressionAnomalyScore}`:'not applicable'));
    l.push(layer('Repeated patch analysis',Number(c.copyMoveSignal)>=70?68:Number(c.copyMoveSignal)>=35?53:35,.7,c.copyMoveSignal!=null,`score ${c.copyMoveSignal??'n/a'}`));
    l.push(layer('Capture pipeline',camera?18:48,.9,true,camera?'Camera/device metadata present':'No camera/device evidence exposed','counter'));
    return l;
  }
  function imageEstimate(data,m){
    const vf=m.visionFusion||{},origin=vf.aiOriginEstimate||{},layers=visionLayers(m);if(!layers.length)layers.push(...fallbackImageLayers(m));
    const proof=proofState(data,m);let score=Number(origin.score);if(!Number.isFinite(score))score=weighted(layers,42);if(proof.verified)score=100;else if(proof.score!=null)score=Math.max(score,proof.score);
    const active=layers.filter(x=>x.available),coverage=Math.round(100*Math.min(1,active.length/Math.max(1,layers.length))),agreement=Number(origin.agreement);const confidence=proof.verified?'verified':Number.isFinite(agreement)&&agreement>=60?'high':active.length>=6?'medium-high':active.length>=4?'medium':'low-medium';
    return{score:clamp(score),layers,proof,coverage,agreement:Number.isFinite(agreement)?clamp(agreement):null,confidence};
  }
  function audioEstimate(m){const w=m.waveform||{},s=txt({container:m.container,streams:m.streams}),l=[];l.push(layer('Generator metadata',/openai|elevenlabs|suno|udio|descript|synthetic|tts|voice clone/.test(s)?94:35,2,true,'Container and stream metadata'));l.push(layer('Waveform repetition',Number(w.identicalSecondBlocks)>1?72:Number(w.identicalSecondBlocks)===1?55:38,1.2,!!w.available,`identical 1s blocks ${w.identicalSecondBlocks??'n/a'}`));l.push(layer('Waveform profile',Math.abs(Number(w.dcOffset)||0)<.00005?52:39,.8,!!w.available,`DC ${w.dcOffset??'n/a'} / clipping ${w.clippedPct??'n/a'}%`));return{score:weighted(l,40),layers:l,coverage:Math.round(l.filter(x=>x.available).length/l.length*100),confidence:'low-medium',proof:{verified:false,label:'Evidence estimate',why:'No authenticated audio provenance or watermark match is retained.'}}}
  function videoEstimate(m){const f=m.frameSampling||{},s=txt({container:m.container,streams:m.streams}),l=[];l.push(layer('Generator metadata',/openai|sora|veo|runway|pika|luma|kling|synthetic|ai generated/.test(s)?96:36,2,true,'Container and stream metadata'));l.push(layer('Temporal noise consistency',f.noiseRange!=null?(f.noiseRange<.35?67:f.noiseRange<1?53:38):45,1.1,f.noiseRange!=null,`range ${f.noiseRange??'n/a'}`));l.push(layer('Temporal edge consistency',f.edgeRange!=null?(f.edgeRange<.8?61:f.edgeRange<2?50:38):45,.8,f.edgeRange!=null,`range ${f.edgeRange??'n/a'}`));l.push(layer('Frame sampling',Number(f.framesSampled)>=5?50:42,.3,Number(f.framesSampled)>0,`${f.framesSampled||0} frames`));return{score:weighted(l,41),layers:l,coverage:Math.round(l.filter(x=>x.available).length/l.length*100),confidence:'low-medium',proof:{verified:false,label:'Evidence estimate',why:'No authenticated video provenance is retained.'}}}
  function pdfEstimate(m){const l=[];l.push(layer('PDF structure',m.pdf?.qpdfOk?40:58,.8,true,m.pdf?.qpdfOk?'qpdf structure valid':'structure needs review'));l.push(layer('OCR composition',m.pdf?.ocrFallbackPages>0&&m.pdf?.digitalTextCharacters<120?48:38,.6,true,`${m.pdf?.ocrFallbackPages||0} OCR pages`));l.push(layer('Signature layer',m.pdf?.signatureToolAvailable?35:45,.4,true,m.pdf?.signatureToolAvailable?'signature inspection available':'no signature evidence'));return{score:weighted(l,39),layers:l,coverage:100,confidence:'low',proof:{verified:false,label:'Evidence estimate',why:'PDF structure alone does not directly identify AI authorship.'}}}
  function originBox(e){const score=e.score,label=e.proof?.verified?'Verified source':score>=80?'Strong AI-origin signal':score>=60?'Elevated AI-origin signal':score>=40?'Mixed origin evidence':'Low AI-origin signal';return `<section class="mmOrigin"><div class="mmOriginTop"><div><div class="eyebrow">EMET EVIDENCE FUSION</div><h3>${esc(label)}</h3><p>${esc(e.proof?.why||'')}</p></div><strong>${score}%</strong></div><div class="mmProofRow"><span class="${e.proof?.verified?'verified':''}">${esc(e.proof?.label||'Evidence estimate')}</span><span>Confidence ${esc(e.confidence||'unknown')}</span><span>Layer coverage ${esc(e.coverage??0)}%</span>${e.agreement!=null?`<span>Agreement ${esc(e.agreement)}%</span>`:''}</div><div class="mmGrid">${e.layers.filter(x=>x.available).map(x=>`<div>${meter(x.label,x.score,x.detail)}</div>`).join('')}</div></section>`}
  function regionList(m){const loc=m?.visionFusion?.localization||{},regions=loc.regions||[];if(!regions.length)return'';return `<details class="advanced mmRegions"><summary>Localized forensic regions (${regions.length})</summary><div class="mmRegionGrid">${regions.slice(0,16).map((r,i)=>`<div><b>Region ${i+1} · ${clamp(r.score)}/100</b><span>x ${Math.round(r.x*100)}% · y ${Math.round(r.y*100)}% · w ${Math.round(r.w*100)}% · h ${Math.round(r.h*100)}%</span><small>${(r.dominant||[]).map(x=>`${esc(x.signal)} ${esc(x.strength)}`).join(' · ')}</small></div>`).join('')}</div></details>`}
  function containerBlock(m){const d=m?.deepContainer||{},c=d.container||{};if(!c.format)return'';return `<details class="advanced"><summary>Deep container history</summary>${kv([['Container',c.format],['Generator markers',(c.generatorMarkers||[]).join(', ')||'None exposed'],['EXIF',c.hasExif?'Present':'Not exposed'],['XMP',c.hasXmp?'Present':'Not exposed'],['Photoshop APP13',c.hasPhotoshopApp13?'Present':'Not exposed'],['ICC profile',c.hasIcc?'Present':'Not exposed'],['JPEG quantization fingerprints',(c.quantizationTableHashes||[]).join(', ')],['Bytes after logical image end',c.trailingBytesAfterEoi??c.trailingBytesAfterIend]])}</details>`}
  function imageCard(data,m){const p=m.pixelForensics||{},r=m.recompression||{},c=m.copyMove||{},ocr=m.ocr||{},receipt=m.receipt||{},e=imageEstimate(data,m),vf=m.visionFusion||{};return `<div class="resultCard mmCard" data-mm="1">${originBox(e)}<div class="resultHead"><div><div class="eyebrow">LOCAL IMAGE FORENSICS</div><h3>Origin, edit localization and retained history</h3></div><span class="miniTag">LOCAL STACK</span></div><p class="sectionLead">EMET fuses the original container, provenance, camera evidence, multi-scale pixel residuals, noise, chroma, JPEG periodicity, recompression, copy-move screening and regional boundary evidence.</p>${regionList(m)}${containerBlock(m)}${kv([['Dimensions',m.dimensions?.width&&m.dimensions?.height?`${m.dimensions.width} × ${m.dimensions.height}`:null],['Format',m.dimensions?.format],['Metadata fields',m.metadata?.fields],['Software',m.metadata?.software],['OCR characters',ocr.characters],['Localization mode',vf.localization?.mode],['Highlighted coverage',vf.localization?.coverage!=null?`${Math.round(vf.localization.coverage*100)}%`:null]])}<details class="advanced"><summary>Pixel measurements</summary>${kv([['Pixel entropy',p.entropy],['Noise residual',p.noiseResidual],['Edge energy',p.edgeEnergy],['8px boundary energy',p.blockBoundaryEnergy],['Clipped pixels',p.clippedPct!=null?`${p.clippedPct}%`:null],['Copy move signal',c.copyMoveSignal],['JPEG recompression',r.recompressionAnomalyScore]])}</details>${receipt.likelyReceipt?receiptCard(receipt):''}</div>`}
  function receiptCard(r){const a=r.arithmetic||{};return `<div class="mmSub"><div class="eyebrow">RECEIPT / INVOICE SCREEN</div><h4>Financial consistency clues</h4>${kv([['Keywords found',(r.keywordHits||[]).join(', ')],['Amounts found',r.amountCount],['Dates',(r.dates||[]).join(', ')],['Largest amount',a.largestAmount],['Best subtotal difference',a.bestPartialSumDifference],['Arithmetic looks consistent',a.consistent===true?'Yes':a.consistent===false?'No':'Not enough data']])}</div>`}
  function pdfCard(data,m){const e=pdfEstimate(m);return `<div class="resultCard mmCard" data-mm="1">${originBox(e)}<div class="resultHead"><div><div class="eyebrow">LOCAL PDF FORENSICS</div><h3>Structure, signatures and OCR coverage</h3></div><span class="miniTag">qpdf + Poppler</span></div>${kv([['Structural check',m.pdf?.qpdfOk?'Passed':'Needs review'],['Digital text characters',m.pdf?.digitalTextCharacters],['OCR fallback pages',m.pdf?.ocrFallbackPages],['Signature inspection',m.pdf?.signatureToolAvailable?'Available':'Unavailable']])}${m.receipt?.likelyReceipt?receiptCard(m.receipt):''}</div>`}
  function audioCard(data,m){const w=m.waveform||{},e=audioEstimate(m);return `<div class="resultCard mmCard" data-mm="1">${originBox(e)}<div class="resultHead"><div><div class="eyebrow">LOCAL AUDIO FORENSICS</div><h3>Container and waveform analysis</h3></div><span class="miniTag">ffmpeg / local</span></div>${kv([['Format',m.container?.format],['Duration',m.container?.duration?`${Math.round(m.container.duration*100)/100}s`:null],['RMS',w.rms],['DC offset',w.dcOffset],['Clipped samples',w.clippedPct!=null?`${w.clippedPct}%`:null],['Zero crossings / sec',w.zeroCrossingsPerSec],['Identical 1s blocks',w.identicalSecondBlocks]])}</div>`}
  function videoCard(data,m){const e=videoEstimate(m);return `<div class="resultCard mmCard" data-mm="1">${originBox(e)}<div class="resultHead"><div><div class="eyebrow">LOCAL VIDEO FORENSICS</div><h3>Container and sampled-frame consistency</h3></div><span class="miniTag">ffmpeg / local</span></div>${kv([['Format',m.container?.format],['Duration',m.container?.duration?`${Math.round(m.container.duration*100)/100}s`:null],['Frames sampled',m.frameSampling?.framesSampled],['Noise variation',m.frameSampling?.noiseRange],['Edge variation',m.frameSampling?.edgeRange]])}</div>`}
  function officeCard(data,m){const imgs=m.images||[];if(!imgs.length)return'';const best=Math.max(...imgs.map(x=>Number(x.syntheticImageSignal?.score)||0)),e={score:clamp(38+best*.5),layers:imgs.map((x,i)=>layer(`Embedded image ${i+1}`,Math.max(8,Number(x.syntheticImageSignal?.score)||0),1,true,x.name)),coverage:100,confidence:'medium',proof:{verified:false,label:'Embedded media estimate',why:'Each embedded image is inspected separately from the document text.'}};return `<div class="resultCard mmCard" data-mm="1">${originBox(e)}<div class="resultHead"><div><div class="eyebrow">EMBEDDED MEDIA</div><h3>Images inside the Office file</h3></div><span class="miniTag">${imgs.length} checked</span></div></div>`}
  function render(data){const m=data?.multimodal;if(!m||['not_checked','not_applicable'].includes(m.status))return'';if(m.kind==='image')return imageCard(data,m);if(m.kind==='pdf')return pdfCard(data,m);if(m.kind==='audio')return audioCard(data,m);if(m.kind==='video')return videoCard(data,m);if(m.kind==='office-embedded-media')return officeCard(data,m);if(m.status==='failed')return `<div class="resultCard mmCard" data-mm="1"><div class="eyebrow">MODALITY CHECK</div><h3>Local media analysis could not complete</h3><p class="sectionLead">${esc(m.error||'Unknown local analyzer error')}</p></div>`;return''}
  function inject(){const results=document.querySelector('#results'),data=window.__EMET_LAST_SCAN;if(!results||!data?.multimodal||results.querySelector('[data-mm]'))return;const html=render(data);if(!html)return;const cards=results.querySelectorAll(':scope > .resultCard');if(cards[0])cards[0].insertAdjacentHTML('beforebegin',html);else results.insertAdjacentHTML('afterbegin',html);if(['image','audio','video'].includes(data.multimodal.kind)){const review=results.querySelector('[data-review-card]');if(review)review.style.display='none';}}
  const style=document.createElement('style');style.textContent=`.mmOrigin{margin:0 0 20px;padding:22px;border:1px solid rgba(47,91,255,.22);border-radius:24px;background:linear-gradient(135deg,rgba(47,91,255,.06),rgba(255,255,255,.96))}.mmOriginTop{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.mmOriginTop h3{margin:8px 0 6px}.mmOriginTop p{margin:0;opacity:.68;max-width:640px}.mmOriginTop>strong{font-size:clamp(48px,14vw,82px);line-height:.9;letter-spacing:-.06em}.mmProofRow{display:flex;flex-wrap:wrap;gap:8px;margin:18px 0}.mmProofRow span{font:600 11px/1.2 ui-monospace,SFMono-Regular,monospace;padding:8px 10px;border:1px solid #ddd;border-radius:999px;background:#fff}.mmProofRow .verified{background:#111;color:#fff;border-color:#111}.mmRegionGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:12px}.mmRegionGrid>div{border:1px solid #e5e5e5;border-radius:16px;padding:12px}.mmRegionGrid b,.mmRegionGrid span,.mmRegionGrid small{display:block}.mmRegionGrid span,.mmRegionGrid small{margin-top:5px;color:#666;font-size:12px}@media(max-width:700px){.mmOrigin{padding:18px}.mmOriginTop{display:block}.mmOriginTop>strong{display:block;margin-top:14px}.mmRegionGrid{grid-template-columns:1fr}}`;document.head.appendChild(style);
  const results=document.querySelector('#results');if(results)new MutationObserver(()=>setTimeout(inject,0)).observe(results,{childList:true,subtree:true});setTimeout(inject,80);
})();
