const fs=require('fs');
const os=require('os');
const path=require('path');
const crypto=require('crypto');
const {execFile}=require('child_process');
const sharp=require('sharp');
const AdmZip=require('adm-zip');

const VERSION='EMET-MULTIMODAL-2026.09.12';
const IMAGE_EXT=new Set(['.jpg','.jpeg','.png','.webp','.tif','.tiff']);
const AUDIO_EXT=new Set(['.wav','.mp3','.m4a','.aac','.flac','.ogg','.opus']);
const VIDEO_EXT=new Set(['.mp4','.mov','.mkv','.webm','.avi','.m4v']);
const OFFICE_EXT=new Set(['.docx','.docm','.pptx','.pptm','.xlsx','.xlsm']);
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
const round=(n,d=3)=>{const p=10**d;return Math.round((Number(n)||0)*p)/p};
const uniq=a=>[...new Set((a||[]).filter(Boolean))];
const tmpPath=ext=>path.join(os.tmpdir(),`emet-${crypto.randomUUID()}${ext||''}`);

function execLocal(bin,args,{timeout=15000,maxBuffer=8*1024*1024,encoding='utf8'}={}){
  return new Promise(resolve=>execFile(bin,args,{timeout,maxBuffer,encoding},(error,stdout,stderr)=>resolve({ok:!error,stdout,stderr,error:error?String(error.message||error):null})));
}
async function withTemp(buffer,ext,fn){const p=tmpPath(ext);fs.writeFileSync(p,buffer);try{return await fn(p)}finally{try{fs.unlinkSync(p)}catch{}}}
function flatMeta(o,p='',out={}){if(!o||typeof o!=='object')return out;for(const[k,v]of Object.entries(o)){const key=p?`${p}.${k}`:k;if(out[key]!==undefined)continue;if(v&&typeof v==='object'&&'description'in v)out[key]=String(v.description);else if(v&&typeof v==='object'&&Object.keys(out).length<160)flatMeta(v,key,out);else if(['string','number','boolean'].includes(typeof v))out[key]=v}return out}
function metadataFingerprint(meta){const s=JSON.stringify(meta||{}).toLowerCase();const names=['openai','chatgpt','gemini','claude','anthropic','midjourney','stable diffusion','firefly','dall-e','sora','imagen','veo','runway','comfyui','automatic1111'];return names.filter(x=>s.includes(x))}

async function rawGray(buffer,max=512){const im=sharp(buffer,{failOn:'none'}).rotate();const m=await im.metadata();const scale=Math.min(1,max/Math.max(m.width||1,m.height||1));const width=Math.max(1,Math.round((m.width||1)*scale)),height=Math.max(1,Math.round((m.height||1)*scale));const {data,info}=await im.resize(width,height,{fit:'fill'}).greyscale().raw().toBuffer({resolveWithObject:true});return{data,width:info.width,height:info.height,meta:m}}
function basicPixelStats({data,width,height}){let sum=0,sum2=0,clip=0;const hist=new Array(256).fill(0);for(const x of data){sum+=x;sum2+=x*x;hist[x]++;if(x<3||x>252)clip++}const n=data.length||1,mean=sum/n,std=Math.sqrt(Math.max(0,sum2/n-mean*mean));let ent=0;for(const c of hist)if(c){const p=c/n;ent-=p*Math.log2(p)}let edge=0,edgeN=0,block=0,blockN=0,noise=0,noiseN=0;for(let y=1;y<height-1;y++){for(let x=1;x<width-1;x++){const i=y*width+x,v=data[i],dx=Math.abs(v-data[i-1]),dy=Math.abs(v-data[i-width]);edge+=dx+dy;edgeN+=2;if(x%8===0){block+=dx;blockN++}if(y%8===0){block+=dy;blockN++}const avg=(data[i-1]+data[i+1]+data[i-width]+data[i+width])/4;noise+=Math.abs(v-avg);noiseN++}}return{mean:round(mean,2),std:round(std,2),entropy:round(ent,3),clippedPct:round(clip/n*100,2),edgeEnergy:round(edge/(edgeN||1),3),blockBoundaryEnergy:round(block/(blockN||1),3),noiseResidual:round(noise/(noiseN||1),3)}}
function copyMoveSignal(gray){const{data,width,height}=gray,tile=16,map=new Map();for(let y=0;y+tile<=height;y+=tile){for(let x=0;x+tile<=width;x+=tile){let sum=0,sum2=0;for(let yy=0;yy<tile;yy++)for(let xx=0;xx<tile;xx++){const v=data[(y+yy)*width+x+xx];sum+=v;sum2+=v*v}const n=tile*tile,mean=Math.round(sum/n/4)*4,std=Math.round(Math.sqrt(Math.max(0,sum2/n-(sum/n)**2))/4)*4;if(std<6)continue;const key=`${mean}:${std}`;const arr=map.get(key)||[];arr.push([x,y]);map.set(key,arr)}}let clusters=0,pairs=0;for(const arr of map.values())if(arr.length>1){for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++){const d=Math.hypot(arr[i][0]-arr[j][0],arr[i][1]-arr[j][1]);if(d>tile*2){pairs++;if(pairs<25)clusters++}}}return{duplicatePatchPairs:pairs,copyMoveSignal:clamp(Math.round(Math.min(1,pairs/20)*100)),note:'Repeated image patches can also come from texture, UI, paper grain or compression. This is not proof of cloning.'}}
async function recompressionSignal(buffer,ext){if(!['.jpg','.jpeg'].includes(ext))return{supported:false,reason:'ELA-style recompression is only interpreted for JPEG in this local baseline.'};try{const base=await rawGray(buffer,384);const recompressed=await sharp(buffer,{failOn:'none'}).jpeg({quality:88,mozjpeg:true}).toBuffer();const b=await rawGray(recompressed,384);const n=Math.min(base.data.length,b.data.length);let sum=0,sum2=0,max=0;for(let i=0;i<n;i++){const d=Math.abs(base.data[i]-b.data[i]);sum+=d;sum2+=d*d;if(d>max)max=d}const mean=sum/(n||1),std=Math.sqrt(Math.max(0,sum2/(n||1)-mean*mean));return{supported:true,meanAbsoluteDifference:round(mean,3),differenceStd:round(std,3),maxDifference:max,recompressionAnomalyScore:clamp(Math.round(mean*4+std*2)),note:'Recompression inconsistency is a forensic indicator, not an AI detector.'}}catch(e){return{supported:false,error:e.message}}}
async function localOcr(buffer,ext){return withTemp(buffer,ext,async p=>{const r=await execLocal('tesseract',[p,'stdout','-l','heb+eng+ara','--psm','6'],{timeout:25000,maxBuffer:6*1024*1024});const text=String(r.stdout||'').trim();return{available:r.ok,characters:text.length,text:text.slice(0,24000),error:r.ok?null:r.error}})}
function receiptSignals(text){const s=String(text||''),lower=s.toLowerCase();const keywords=['receipt','invoice','total','subtotal','tax','vat','amount','קבלה','חשבונית','סה"כ','סה״כ','מע"מ','מע״מ','לתשלום','שולם'];const hits=keywords.filter(k=>lower.includes(k.toLowerCase()));const amounts=[...s.matchAll(/(?:₪|\$|€|£|USD|ILS|EUR)?\s*(-?\d{1,7}(?:[,.]\d{1,2})?)(?:\s*(?:₪|\$|€|£|USD|ILS|EUR))?/g)].map(m=>Number(m[1].replace(',','.'))).filter(n=>Number.isFinite(n)&&n>0&&n<1e8);const dates=[...s.matchAll(/\b(?:\d{1,2}[\/.\-]\d{1,2}[\/.\-](?:20)?\d{2,4}|(?:20)\d{2}[\/.\-]\d{1,2}[\/.\-]\d{1,2})\b/g)].map(m=>m[0]).slice(0,12);const likely=hits.length>=2||(/₪|ILS|USD|EUR/.test(s)&&amounts.length>=3);let arithmetic=null;if(likely&&amounts.length>=3){const sorted=[...amounts].sort((a,b)=>b-a),top=sorted[0],rest=amounts.filter((_,i)=>i!==amounts.indexOf(top));let best=Infinity,bestCount=0;for(let i=0;i<Math.min(rest.length,12);i++){let sum=0;for(let j=i;j<Math.min(rest.length,i+8);j++){sum+=rest[j];const diff=Math.abs(sum-top);if(diff<best){best=diff;bestCount=j-i+1}}}arithmetic={largestAmount:top,bestPartialSumDifference:round(best,2),itemsInBestSum:bestCount,consistent:best<=Math.max(.05,top*.01)}}return{likelyReceipt:likely,keywordHits:hits,amountCount:amounts.length,amountSample:amounts.slice(0,20),dates,arithmetic}}
async function imageAnalysis(buffer,ext){const gray=await rawGray(buffer,512),stats=basicPixelStats(gray),copy=copyMoveSignal(gray),ela=await recompressionSignal(buffer,ext);let meta={};try{const ExifReader=require('exifreader');meta=flatMeta(ExifReader.load(buffer,{expanded:true}))}catch{}const ocr=await localOcr(buffer,ext).catch(e=>({available:false,error:e.message,text:''})),receipt=receiptSignals(ocr.text);const fingerprints=metadataFingerprint(meta);let syntheticScore=0,reasons=[];if(fingerprints.length){syntheticScore+=65;reasons.push(`Generator metadata mentions: ${fingerprints.join(', ')}`)}if(ela.supported&&ela.recompressionAnomalyScore>=65){syntheticScore+=12;reasons.push('JPEG recompression differences are unusually uneven.')}if(copy.copyMoveSignal>=70){syntheticScore+=10;reasons.push('Repeated non-adjacent patch fingerprints deserve manipulation review.')}if(stats.noiseResidual<1.8&&stats.edgeEnergy>8){syntheticScore+=8;reasons.push('Very low local noise relative to edge energy is unusual for some camera pipelines.')}syntheticScore=clamp(syntheticScore);return{kind:'image',status:'completed',dimensions:{width:gray.meta.width||null,height:gray.meta.height||null,format:gray.meta.format||null},metadata:{fields:Object.keys(meta).length,software:Object.entries(meta).find(([k])=>/software/i.test(k))?.[1]||null,generatorFingerprints:fingerprints},pixelForensics:stats,recompression:ela,copyMove:copy,ocr:{available:ocr.available,characters:ocr.characters||0,textPreview:String(ocr.text||'').slice(0,1500)},receipt,syntheticImageSignal:{score:syntheticScore,reasons,calibrated:false},coverage:{pixelsAnalyzed:gray.data.length,ocr:ocr.available,metadata:true},limitations:['Pixel and recompression features are local forensic signals, not universal proof of AI generation.','Messaging apps and re-encoding can destroy metadata and alter forensic traces.','The local image classifier is not yet a trained UniversalFakeDetect-equivalent model; this result does not pretend otherwise.']}}
async function pdfAnalysis(file){const ext='.pdf';return withTemp(file.buffer,ext,async p=>{const [info,sig,check,text]=await Promise.all([execLocal('pdfinfo',[p],{timeout:12000}),execLocal('pdfsig',[p],{timeout:15000}),execLocal('qpdf',['--check',p],{timeout:12000}),execLocal('pdftotext',['-layout',p,'-'],{timeout:15000,maxBuffer:10*1024*1024})]);let ocrText='',ocrPages=0;if(String(text.stdout||'').replace(/\s/g,'').length<120){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'emet-pdf-'));try{const prefix=path.join(dir,'page');await execLocal('pdftoppm',['-f','1','-l','3','-r','160','-png',p,prefix],{timeout:25000,maxBuffer:2*1024*1024});const imgs=fs.readdirSync(dir).filter(x=>x.endsWith('.png')).sort();for(const name of imgs){const buf=fs.readFileSync(path.join(dir,name));const o=await localOcr(buf,'.png');if(o.text){ocrText+=`\n${o.text}`;ocrPages++}}}finally{try{fs.rmSync(dir,{recursive:true,force:true})}catch{}}}const combined=(String(text.stdout||'')+'\n'+ocrText).trim(),receipt=receiptSignals(combined);return{kind:'pdf',status:'completed',pdf:{info:String(info.stdout||'').slice(0,5000),qpdfOk:check.ok,qpdfMessage:String(check.stderr||check.stdout||'').slice(0,2000),signatureToolAvailable:sig.ok||Boolean(sig.stdout),signatureReport:String(sig.stdout||sig.stderr||'').slice(0,5000),digitalTextCharacters:String(text.stdout||'').length,ocrFallbackPages:ocrPages},receipt,coverage:{digitalText:String(text.stdout||'').length>0,ocrFallback:ocrPages>0,pagesOcrd:ocrPages,signatureInspection:true,structuralCheck:true},limitations:['A PDF signature report must be interpreted separately as cryptographic validity, certificate trust and post-signature modifications.','OCR is used only when the digital text layer is sparse; OCR errors lower evidentiary confidence.']}})}
function parseFfprobe(s){try{return JSON.parse(String(s||'{}'))}catch{return{}}}
async function probeMedia(p){const r=await execLocal('ffprobe',['-v','error','-print_format','json','-show_format','-show_streams',p],{timeout:15000,maxBuffer:4*1024*1024});return{ok:r.ok,data:parseFfprobe(r.stdout),error:r.error}}
async function audioPcmStats(p){const r=await execLocal('ffmpeg',['-v','error','-i',p,'-t','60','-vn','-ac','1','-ar','16000','-f','s16le','pipe:1'],{timeout:30000,maxBuffer:4*1024*1024,encoding:null});if(!r.ok||!Buffer.isBuffer(r.stdout))return{available:false,error:r.error};const b=r.stdout,n=Math.floor(b.length/2);if(!n)return{available:false};let sum=0,sum2=0,clip=0,zc=0,prev=0;const secHashes=[];let sec=[];for(let i=0;i<n;i++){const v=b.readInt16LE(i*2)/32768;sum+=v;sum2+=v*v;if(Math.abs(v)>.995)clip++;if(i&&((v>=0)!=(prev>=0)))zc++;prev=v;sec.push(Math.round(v*127));if(sec.length===16000){secHashes.push(crypto.createHash('sha1').update(Buffer.from(sec.map(x=>x+128))).digest('hex').slice(0,12));sec=[]}}const mean=sum/n,rms=Math.sqrt(sum2/n),repeats=secHashes.length-new Set(secHashes).size;return{available:true,durationSampledSec:round(n/16000,2),rms:round(rms,5),dcOffset:round(mean,5),clippedPct:round(clip/n*100,4),zeroCrossingsPerSec:round(zc/(n/16000),2),identicalSecondBlocks:repeats,signal:'time-domain baseline only'}}
async function audioAnalysis(file){const ext=path.extname(file.originalname||'').toLowerCase();return withTemp(file.buffer,ext,async p=>{const probe=await probeMedia(p),pcm=await audioPcmStats(p);const fmt=probe.data?.format||{},streams=probe.data?.streams||[];return{kind:'audio',status:'completed',container:{duration:Number(fmt.duration)||null,bitRate:Number(fmt.bit_rate)||null,format:fmt.format_name||null,tags:fmt.tags||{}},streams:streams.map(x=>({codec_type:x.codec_type,codec_name:x.codec_name,sample_rate:x.sample_rate,channels:x.channels,bit_rate:x.bit_rate,tags:x.tags||{}})),waveform:pcm,watermark:{audioSeal:'not_checked',reason:'AudioSeal model weights are not bundled in this deployment yet.'},coverage:{container:true,timeDomain:pcm.available,watermark:false},limitations:['This local audio baseline checks container and waveform continuity features; it is not yet a trained deepfake voice classifier.','Codec conversion and denoising can alter waveform statistics.']}})}
async function frameAt(p,t,out){return (await execLocal('ffmpeg',['-v','error','-ss',String(Math.max(0,t)),'-i',p,'-frames:v','1','-vf','scale=640:-2',out],{timeout:20000,maxBuffer:2*1024*1024})).ok}
async function videoAnalysis(file){const ext=path.extname(file.originalname||'').toLowerCase();return withTemp(file.buffer,ext,async p=>{const probe=await probeMedia(p),fmt=probe.data?.format||{},duration=Number(fmt.duration)||0,dir=fs.mkdtempSync(path.join(os.tmpdir(),'emet-video-'));const frames=[];try{const points=duration>0?[.08,.28,.5,.72,.92].map(x=>duration*x):[0,1,2];for(let i=0;i<points.length;i++){const out=path.join(dir,`f${i}.jpg`);if(await frameAt(p,points[i],out)&&fs.existsSync(out)){const buf=fs.readFileSync(out),gray=await rawGray(buf,320),stats=basicPixelStats(gray);frames.push({time:round(points[i],2),...stats})}}}finally{try{fs.rmSync(dir,{recursive:true,force:true})}catch{}}const noise=frames.map(x=>x.noiseResidual),edge=frames.map(x=>x.edgeEnergy),range=a=>a.length?round(Math.max(...a)-Math.min(...a),3):null;return{kind:'video',status:'completed',container:{duration:duration||null,format:fmt.format_name||null,bitRate:Number(fmt.bit_rate)||null,tags:fmt.tags||{}},streams:(probe.data?.streams||[]).map(x=>({codec_type:x.codec_type,codec_name:x.codec_name,width:x.width,height:x.height,r_frame_rate:x.r_frame_rate,sample_rate:x.sample_rate,channels:x.channels,tags:x.tags||{}})),frameSampling:{framesSampled:frames.length,frames,noiseRange:range(noise),edgeRange:range(edge)},coverage:{container:true,framesSampled:frames.length,faceDeepfakeModel:false,lipSyncModel:false},limitations:['Frame sampling does not equal full-video deepfake detection.','Face-swap, lip-sync and temporal neural classifiers are not yet bundled in this deployment; EMET reports them as not checked instead of inventing a result.']}})}
async function officeMediaAnalysis(file){const ext=path.extname(file.originalname||'').toLowerCase();if(!OFFICE_EXT.has(ext))return null;let zip;try{zip=new AdmZip(file.buffer)}catch{return null}const entries=zip.getEntries().filter(e=>/(?:word|ppt|xl)\/media\/[^/]+$/i.test(e.entryName)&&!e.isDirectory).slice(0,6),images=[];for(const e of entries){const x=path.extname(e.entryName).toLowerCase();if(!IMAGE_EXT.has(x))continue;try{const a=await imageAnalysis(e.getData(),x);images.push({name:e.entryName,syntheticImageSignal:a.syntheticImageSignal,metadata:a.metadata,pixelForensics:a.pixelForensics,recompression:a.recompression,copyMove:a.copyMove})}catch(err){images.push({name:e.entryName,error:err.message})}}return{kind:'office-embedded-media',status:'completed',imagesChecked:images.length,images,coverage:{embeddedMediaEntries:entries.length,imagesChecked:images.length},limitations:['An AI-generated embedded image does not imply that the surrounding document text was AI-generated.']}}
async function analyzeMultimodal(file){const ext=path.extname(file.originalname||'').toLowerCase();try{if(IMAGE_EXT.has(ext))return await imageAnalysis(file.buffer,ext);if(ext==='.pdf')return await pdfAnalysis(file);if(AUDIO_EXT.has(ext))return await audioAnalysis(file);if(VIDEO_EXT.has(ext))return await videoAnalysis(file);if(OFFICE_EXT.has(ext))return await officeMediaAnalysis(file)||{kind:'office',status:'no-embedded-media'};return{kind:'unsupported-for-multimodal',status:'not_checked',reason:'No modality-specific local pipeline is defined for this file type.'}}catch(e){return{kind:'unknown',status:'failed',error:String(e.message||e),limitations:['A modality-specific local analysis failed; this failure must not be interpreted as evidence that the file is authentic.']}}
}
module.exports={analyzeMultimodal,imageAnalysis,receiptSignals};
