(()=>{
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=v=>v===null||v===undefined||v===''?'Not available':typeof v==='number'?String(Math.round(v*1000)/1000):String(v);
  const meter=(label,value,help)=>{const n=Math.max(0,Math.min(100,Number(value)||0));return `<div class="mmMeter"><div><b>${esc(label)}</b><span>${esc(help)}</span></div><strong>${Math.round(n)}</strong><i><u style="width:${n}%"></u></i></div>`};
  const kv=(rows)=>`<div class="mmKv">${rows.filter(([,v])=>v!==null&&v!==undefined&&v!=='').map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(fmt(v))}</b></div>`).join('')}</div>`;
  function imageCard(m){const p=m.pixelForensics||{},r=m.recompression||{},c=m.copyMove||{},s=m.syntheticImageSignal||{},ocr=m.ocr||{},receipt=m.receipt||{};return `<div class="resultCard mmCard" data-mm="1"><div class="resultHead"><div><div class="eyebrow">LOCAL IMAGE FORENSICS</div><h3>What the pixels and metadata say</h3></div><span class="miniTag">No external API</span></div><p class="sectionLead">EMET analyzes the original bytes before resizing, then separates metadata, pixel statistics, recompression, repeated-patch screening and OCR. None of these alone is treated as proof.</p><div class="mmGrid"><div>${meter('Synthetic-image signal',s.score||0,'Combined local forensic signal. Not a calibrated probability.')}</div><div>${meter('Copy-move screening',c.copyMoveSignal||0,'Repeated non-adjacent patch fingerprints.')}</div>${r.supported?`<div>${meter('JPEG recompression anomaly',r.recompressionAnomalyScore||0,'Uneven error after controlled recompression.')}</div>`:''}</div>${kv([['Dimensions',m.dimensions?.width&&m.dimensions?.height?`${m.dimensions.width} × ${m.dimensions.height}`:null],['Format',m.dimensions?.format],['Metadata fields',m.metadata?.fields],['Software',m.metadata?.software],['OCR characters',ocr.characters],['Receipt-like document',receipt.likelyReceipt?'Yes':'No']])}${s.reasons?.length?`<div class="whyBox"><b>Why this layer noticed something</b>${s.reasons.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}<details class="advanced"><summary>Pixel and OCR details</summary>${kv([['Pixel entropy',p.entropy],['Noise residual',p.noiseResidual],['Edge energy',p.edgeEnergy],['8px boundary energy',p.blockBoundaryEnergy],['Clipped pixels',p.clippedPct!=null?`${p.clippedPct}%`:null],['Duplicate patch pairs',c.duplicatePatchPairs],['OCR preview',ocr.textPreview]])}</details>${receipt.likelyReceipt?receiptCard(receipt):''}</div>`}
  function receiptCard(r){const a=r.arithmetic||{};return `<div class="mmSub"><div class="eyebrow">RECEIPT / INVOICE SCREEN</div><h4>Financial consistency clues</h4>${kv([['Keywords found',(r.keywordHits||[]).join(', ')],['Amounts found',r.amountCount],['Dates',(r.dates||[]).join(', ')],['Largest amount',a.largestAmount],['Best subtotal difference',a.bestPartialSumDifference],['Arithmetic looks consistent',a.consistent===true?'Yes':a.consistent===false?'No':'Not enough data']])}<p>This does not verify that a transaction actually happened. Source-system matching is a separate evidence layer.</p></div>`}
  function pdfCard(m){return `<div class="resultCard mmCard" data-mm="1"><div class="resultHead"><div><div class="eyebrow">LOCAL PDF FORENSICS</div><h3>Structure, signatures and OCR coverage</h3></div><span class="miniTag">qpdf + Poppler</span></div>${kv([['Structural check',m.pdf?.qpdfOk?'Passed':'Needs review'],['Digital text characters',m.pdf?.digitalTextCharacters],['OCR fallback pages',m.pdf?.ocrFallbackPages],['Signature inspection',m.pdf?.signatureToolAvailable?'Available':'Unavailable']])}${m.receipt?.likelyReceipt?receiptCard(m.receipt):''}<details class="advanced"><summary>Signature and structural report</summary>${kv([['Signature report',m.pdf?.signatureReport],['qpdf report',m.pdf?.qpdfMessage],['PDF info',m.pdf?.info]])}</details></div>`}
  function audioCard(m){const w=m.waveform||{};return `<div class="resultCard mmCard" data-mm="1"><div class="resultHead"><div><div class="eyebrow">LOCAL AUDIO FORENSICS</div><h3>Container and waveform baseline</h3></div><span class="miniTag">ffmpeg / local</span></div>${kv([['Format',m.container?.format],['Duration',m.container?.duration?`${Math.round(m.container.duration*100)/100}s`:null],['RMS',w.rms],['DC offset',w.dcOffset],['Clipped samples',w.clippedPct!=null?`${w.clippedPct}%`:null],['Zero crossings / sec',w.zeroCrossingsPerSec],['Identical 1s blocks',w.identicalSecondBlocks]])}<div class="notice">Voice deepfake and AudioSeal neural models are shown as not checked until their model weights are actually bundled. EMET does not convert a missing detector into a clean result.</div></div>`}
  function videoCard(m){return `<div class="resultCard mmCard" data-mm="1"><div class="resultHead"><div><div class="eyebrow">LOCAL VIDEO FORENSICS</div><h3>Container and sampled-frame consistency</h3></div><span class="miniTag">ffmpeg / local</span></div>${kv([['Format',m.container?.format],['Duration',m.container?.duration?`${Math.round(m.container.duration*100)/100}s`:null],['Frames sampled',m.frameSampling?.framesSampled],['Noise variation',m.frameSampling?.noiseRange],['Edge variation',m.frameSampling?.edgeRange]])}<details class="advanced"><summary>Sampled frame measurements</summary>${kv((m.frameSampling?.frames||[]).map((x,i)=>[`Frame ${i+1} at ${x.time}s`,`noise ${x.noiseResidual}, edge ${x.edgeEnergy}, entropy ${x.entropy}`]))}</details><div class="notice">Face-swap and lip-sync neural classifiers are intentionally marked not checked until local models are bundled and benchmarked.</div></div>`}
  function officeCard(m){const imgs=m.images||[];if(!imgs.length)return'';return `<div class="resultCard mmCard" data-mm="1"><div class="resultHead"><div><div class="eyebrow">EMBEDDED MEDIA</div><h3>Images inside the Office file</h3></div><span class="miniTag">${imgs.length} checked</span></div><p class="sectionLead">Embedded images are inspected separately from the document text. A synthetic image does not make the surrounding writing synthetic.</p><div class="mmEmbedded">${imgs.map(x=>`<div><b>${esc(x.name)}</b><span>image signal ${Math.round(x.syntheticImageSignal?.score||0)}/100</span><small>${esc((x.metadata?.generatorFingerprints||[]).join(', ')||'No generator metadata found')}</small></div>`).join('')}</div></div>`}
  function render(m){if(!m||['not_checked','not_applicable'].includes(m.status))return'';if(m.kind==='image')return imageCard(m);if(m.kind==='pdf')return pdfCard(m);if(m.kind==='audio')return audioCard(m);if(m.kind==='video')return videoCard(m);if(m.kind==='office-embedded-media')return officeCard(m);if(m.status==='failed')return `<div class="resultCard mmCard" data-mm="1"><div class="eyebrow">MODALITY CHECK</div><h3>Local media analysis could not complete</h3><p class="sectionLead">${esc(m.error||'Unknown local analyzer error')}</p></div>`;return''}
  function inject(){const results=document.querySelector('#results'),data=window.__EMET_LAST_SCAN;if(!results||!data?.multimodal||results.querySelector('[data-mm]'))return;const html=render(data.multimodal);if(!html)return;const cards=results.querySelectorAll(':scope > .resultCard');if(cards[0])cards[0].insertAdjacentHTML('afterend',html);else results.insertAdjacentHTML('afterbegin',html)}
  const results=document.querySelector('#results');if(results)new MutationObserver(()=>setTimeout(inject,0)).observe(results,{childList:true,subtree:false});
})();
