(()=>{
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=v=>v===null||v===undefined||v===''?'Not available':typeof v==='number'?String(Math.round(v*1000)/1000):String(v);
  const clamp=n=>Math.max(1,Math.min(99,Math.round(Number(n)||0)));
  const txt=v=>JSON.stringify(v||{}).toLowerCase();
  const meter=(label,value,help)=>{const n=Math.max(0,Math.min(100,Number(value)||0));return `<div class="mmMeter"><div><b>${esc(label)}</b><span>${esc(help)}</span></div><strong>${Math.round(n)}</strong><i><u style="width:${n}%"></u></i></div>`};
  const kv=(rows)=>`<div class="mmKv">${rows.filter(([,v])=>v!==null&&v!==undefined&&v!=='').map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(fmt(v))}</b></div>`).join('')}</div>`;
  function layer(label,score,weight,available=true,detail=''){return{label,score:clamp(score),weight,available:Boolean(available),detail}}
  function weighted(layers,prior=40){const a=layers.filter(x=>x.available&&x.weight>0);if(!a.length)return clamp(prior);let sw=0,s=0;for(const x of a){sw+=x.weight;s+=x.score*x.weight}const raw=s/sw,blend=Math.min(.88,.28+sw/12);return clamp(prior*(1-blend)+raw*blend)}
  function imageEstimate(m){const p=m.pixelForensics||{},r=m.recompression||{},c=m.copyMove||{},s=m.syntheticImageSignal||{},meta=m.metadata||{},gens=meta.generatorFingerprints||[],all=txt(meta),camera=/iphone|samsung|pixel|canon|nikon|sony|fujifilm|olympus|panasonic|leica|huawei|xiaomi/.test(all),l=[];
    l.push(layer('Generator fingerprint',gens.length?99:18,3,true,gens.length?gens.join(', '):'No exposed generator name'));
    l.push(layer('Pixel forensic fusion',Math.max(8,Number(s.score)||0),2,true,'Existing local pixel and metadata analysis'));
    l.push(layer('Noise residual',p.noiseResidual<1.8&&p.edgeEnergy>8?78:p.noiseResidual<3?58:34,1.2,p.noiseResidual!=null,`noise ${p.noiseResidual??'n/a'} / edge ${p.edgeEnergy??'n/a'}`));
    l.push(layer('Texture entropy',p.entropy>7.7?42:p.entropy<5.2?63:48,.7,p.entropy!=null,`entropy ${p.entropy??'n/a'}`));
    l.push(layer('JPEG recompression',r.supported?Math.max(15,Number(r.recompressionAnomalyScore)||0):45,.8,!!r.supported,r.supported?`score ${r.recompressionAnomalyScore}`:'not applicable'));
    l.push(layer('Repeated patch analysis',Number(c.copyMoveSignal)>=70?68:Number(c.copyMoveSignal)>=35?53:35,.7,c.copyMoveSignal!=null,`score ${c.copyMoveSignal??'n/a'}`));
    l.push(layer('Capture pipeline',camera?18:48,1,true,camera?'Camera or device metadata present':'No camera or device evidence exposed'));
    return{score:weighted(l,42),layers:l};
  }
  function audioEstimate(m){const w=m.waveform||{},s=txt({container:m.container,streams:m.streams}),l=[];l.push(layer('Generator metadata',/openai|elevenlabs|suno|udio|descript|synthetic|tts|voice clone/.test(s)?94:35,2,true,'Container and stream metadata'));l.push(layer('Waveform repetition',Number(w.identicalSecondBlocks)>1?72:Number(w.identicalSecondBlocks)===1?55:38,1.2,!!w.available,`identical 1s blocks ${w.identicalSecondBlocks??'n/a'}`));l.push(layer('Waveform profile',Math.abs(Number(w.dcOffset)||0)<.00005?52:39,.8,!!w.available,`DC ${w.dcOffset??'n/a'} / clipping ${w.clippedPct??'n/a'}%`));return{score:weighted(l,40),layers:l}}
  function videoEstimate(m){const f=m.frameSampling||{},s=txt({container:m.container,streams:m.streams}),l=[];l.push(layer('Generator metadata',/openai|sora|veo|runway|pika|luma|kling|synthetic|ai generated/.test(s)?96:36,2,true,'Container and stream metadata'));l.push(layer('Temporal noise consistency',f.noiseRange!=null?(f.noiseRange<.35?67:f.noiseRange<1?53:38):45,1.1,f.noiseRange!=null,`range ${f.noiseRange??'n/a'}`));l.push(layer('Temporal edge consistency',f.edgeRange!=null?(f.edgeRange<.8?61:f.edgeRange<2?50:38):45,.8,f.edgeRange!=null,`range ${f.edgeRange??'n/a'}`));l.push(layer('Frame sampling',Number(f.framesSampled)>=5?50:42,.3,Number(f.framesSampled)>0,`${f.framesSampled||0} frames`));return{score:weighted(l,41),layers:l}}
  function pdfEstimate(m){const l=[];l.push(layer('PDF structure',m.pdf?.qpdfOk?40:58,.8,true,m.pdf?.qpdfOk?'qpdf structure valid':'structure needs review'));l.push(layer('OCR composition',m.pdf?.ocrFallbackPages>0&&m.pdf?.digitalTextCharacters<120?48:38,.6,true,`${m.pdf?.ocrFallbackPages||0} OCR pages`));l.push(layer('Signature layer',m.pdf?.signatureToolAvailable?35:45,.4,true,m.pdf?.signatureToolAvailable?'signature inspection available':'no signature evidence'));return{score:weighted(l,39),layers:l}}
  function originBox(e){const score=e.score,confidence=e.layers.filter(x=>x.available).length>=5?'medium':e.layers.filter(x=>x.available).length>=3?'low-medium':'low',label=score>=75?'High AI signal':score>=55?'Elevated AI signal':score>=35?'Mixed evidence':'Low AI signal';return `<section style="margin:0 0 20px;padding:22px;border:1px solid rgba(47,91,255,.22);border-radius:24px;background:linear-gradient(135deg,rgba(47,91,255,.06),rgba(255,255,255,.95))"><div style="display:flex;justify-content:space-between;gap:18px;align-items:flex-start"><div><div class="eyebrow">EMET AI ORIGIN ESTIMATE</div><h3 style="margin:8px 0 6px">${esc(label)}</h3><p style="margin:0;opacity:.68">Confidence: ${esc(confidence)}</p></div><strong style="font-size:clamp(48px,14vw,82px);line-height:.9;letter-spacing:-.06em">${score}%</strong></div><p class="sectionLead" style="margin-top:18px">A percentage is always produced by fusing the local evidence layers below. It is an origin estimate, not a claim of mathematical certainty.</p><div class="mmGrid">${e.layers.filter(x=>x.available).map(x=>`<div>${meter(x.label,x.score,x.detail)}</div>`).join('')}</div></section>`}
  function imageCard(m){const p=m.pixelForensics||{},r=m.recompression||{},c=m.copyMove||{},s=m.syntheticImageSignal||{},ocr=m.ocr||{},receipt=m.receipt||{},e=imageEstimate(m);return `<div class="resultCard mmCard" data-mm="1">${originBox(e)}<div class="resultHead"><div><div class="eyebrow">LOCAL IMAGE FORENSICS</div><h3>What the pixels and metadata say</h3></div><span class="miniTag">No external API</span></div><p class="sectionLead">EMET analyzes the original bytes before resizing, then separates metadata, pixel statistics, recompression, repeated-patch screening and OCR.</p><div class="mmGrid"><div>${meter('Raw synthetic-image signal',s.score||0,'One local forensic layer inside the larger ensemble.')}</div><div>${meter('Copy-move screening',c.copyMoveSignal||0,'Repeated non-adjacent patch fingerprints.')}</div>${r.supported?`<div>${meter('JPEG recompression anomaly',r.recompressionAnomalyScore||0,'Uneven error after controlled recompression.')}</div>`:''}</div>${kv([['Dimensions',m.dimensions?.width&&m.dimensions?.height?`${m.dimensions.width} × ${m.dimensions.height}`:null],['Format',m.dimensions?.format],['Metadata fields',m.metadata?.fields],['Software',m.metadata?.software],['OCR characters',ocr.characters],['Receipt-like document',receipt.likelyReceipt?'Yes':'No']])}${s.reasons?.length?`<div class="whyBox"><b>Why this layer noticed something</b>${s.reasons.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}<details class="advanced"><summary>Pixel and OCR details</summary>${kv([['Pixel entropy',p.entropy],['Noise residual',p.noiseResidual],['Edge energy',p.edgeEnergy],['8px boundary energy',p.blockBoundaryEnergy],['Clipped pixels',p.clippedPct!=null?`${p.clippedPct}%`:null],['Duplicate patch pairs',c.duplicatePatchPairs],['OCR preview',ocr.textPreview]])}</details>${receipt.likelyReceipt?receiptCard(receipt):''}</div>`}
  function receiptCard(r){const a=r.arithmetic||{};return `<div class="mmSub"><div class="eyebrow">RECEIPT / INVOICE SCREEN</div><h4>Financial consistency clues</h4>${kv([['Keywords found',(r.keywordHits||[]).join(', ')],['Amounts found',r.amountCount],['Dates',(r.dates||[]).join(', ')],['Largest amount',a.largestAmount],['Best subtotal difference',a.bestPartialSumDifference],['Arithmetic looks consistent',a.consistent===true?'Yes':a.consistent===false?'No':'Not enough data']])}<p>This does not verify that a transaction actually happened. Source-system matching is a separate evidence layer.</p></div>`}
  function pdfCard(m){const e=pdfEstimate(m);return `<div class="resultCard mmCard" data-mm="1">${originBox(e)}<div class="resultHead"><div><div class="eyebrow">LOCAL PDF FORENSICS</div><h3>Structure, signatures and OCR coverage</h3></div><span class="miniTag">qpdf + Poppler</span></div>${kv([['Structural check',m.pdf?.qpdfOk?'Passed':'Needs review'],['Digital text characters',m.pdf?.digitalTextCharacters],['OCR fallback pages',m.pdf?.ocrFallbackPages],['Signature inspection',m.pdf?.signatureToolAvailable?'Available':'Unavailable']])}${m.receipt?.likelyReceipt?receiptCard(m.receipt):''}<details class="advanced"><summary>Signature and structural report</summary>${kv([['Signature report',m.pdf?.signatureReport],['qpdf report',m.pdf?.qpdfMessage],['PDF info',m.pdf?.info]])}</details></div>`}
  function audioCard(m){const w=m.waveform||{},e=audioEstimate(m);return `<div class="resultCard mmCard" data-mm="1">${originBox(e)}<div class="resultHead"><div><div class="eyebrow">LOCAL AUDIO FORENSICS</div><h3>Container and waveform analysis</h3></div><span class="miniTag">ffmpeg / local</span></div>${kv([['Format',m.container?.format],['Duration',m.container?.duration?`${Math.round(m.container.duration*100)/100}s`:null],['RMS',w.rms],['DC offset',w.dcOffset],['Clipped samples',w.clippedPct!=null?`${w.clippedPct}%`:null],['Zero crossings / sec',w.zeroCrossingsPerSec],['Identical 1s blocks',w.identicalSecondBlocks]])}</div>`}
  function videoCard(m){const e=videoEstimate(m);return `<div class="resultCard mmCard" data-mm="1">${originBox(e)}<div class="resultHead"><div><div class="eyebrow">LOCAL VIDEO FORENSICS</div><h3>Container and sampled-frame consistency</h3></div><span class="miniTag">ffmpeg / local</span></div>${kv([['Format',m.container?.format],['Duration',m.container?.duration?`${Math.round(m.container.duration*100)/100}s`:null],['Frames sampled',m.frameSampling?.framesSampled],['Noise variation',m.frameSampling?.noiseRange],['Edge variation',m.frameSampling?.edgeRange]])}<details class="advanced"><summary>Sampled frame measurements</summary>${kv((m.frameSampling?.frames||[]).map((x,i)=>[`Frame ${i+1} at ${x.time}s`,`noise ${x.noiseResidual}, edge ${x.edgeEnergy}, entropy ${x.entropy}`]))}</details></div>`}
  function officeCard(m){const imgs=m.images||[];if(!imgs.length)return'';const best=Math.max(...imgs.map(x=>Number(x.syntheticImageSignal?.score)||0)),e={score:clamp(38+best*.5),layers:imgs.map((x,i)=>layer(`Embedded image ${i+1}`,Math.max(8,Number(x.syntheticImageSignal?.score)||0),1,true,x.name))};return `<div class="resultCard mmCard" data-mm="1">${originBox(e)}<div class="resultHead"><div><div class="eyebrow">EMBEDDED MEDIA</div><h3>Images inside the Office file</h3></div><span class="miniTag">${imgs.length} checked</span></div><div class="mmEmbedded">${imgs.map(x=>`<div><b>${esc(x.name)}</b><span>image signal ${Math.round(x.syntheticImageSignal?.score||0)}/100</span><small>${esc((x.metadata?.generatorFingerprints||[]).join(', ')||'No generator metadata found')}</small></div>`).join('')}</div></div>`}
  function render(m){if(!m||['not_checked','not_applicable'].includes(m.status))return'';if(m.kind==='image')return imageCard(m);if(m.kind==='pdf')return pdfCard(m);if(m.kind==='audio')return audioCard(m);if(m.kind==='video')return videoCard(m);if(m.kind==='office-embedded-media')return officeCard(m);if(m.status==='failed')return `<div class="resultCard mmCard" data-mm="1"><div class="eyebrow">MODALITY CHECK</div><h3>Local media analysis could not complete</h3><p class="sectionLead">${esc(m.error||'Unknown local analyzer error')}</p></div>`;return''}
  function inject(){const results=document.querySelector('#results'),data=window.__EMET_LAST_SCAN;if(!results||!data?.multimodal||results.querySelector('[data-mm]'))return;const html=render(data.multimodal);if(!html)return;const cards=results.querySelectorAll(':scope > .resultCard');if(cards[0])cards[0].insertAdjacentHTML('beforebegin',html);else results.insertAdjacentHTML('afterbegin',html);if(['image','audio','video'].includes(data.multimodal.kind)){const review=results.querySelector('[data-review-card]');if(review){const h=review.querySelector('h2');if(h)h.textContent='Technical evidence detail';const p=review.querySelector('.reviewLead');if(p)p.textContent='The AI origin percentage is shown above. This section keeps the raw observations and coverage details.'}}}
  const results=document.querySelector('#results');if(results)new MutationObserver(()=>setTimeout(inject,0)).observe(results,{childList:true,subtree:true});setTimeout(inject,80);
})();
