'use strict';
const FEATURES=['processScore','documentSignalScore','rhythm','lexical','discourse','surfaceStyle','predictability','aiResidue','fingerprintCoverage','rsidCount','trackedChanges','metadataLifetimeMinutes','zipUniqueTimes','imageOriginScore','visionAgreement','regionStrength','boundaryAdhesion','sensorPatternAnomaly','spectralLatticeAnomaly','globalGenerativePrior','containerSignalScore','cameraEvidenceScore','recompressionScore','copyMoveScore','cfaParity','jpegPhaseContrast','flatNoise','highPass','edgeEnergy','chromaStd','entropy','audioGeneratorScore','audioRepeatBlocks','videoNoiseConsistency','videoEdgeConsistency','provenanceVerified','groundTruthExact'];
const sigmoid=z=>1/(1+Math.exp(-Math.max(-35,Math.min(35,z))));
const mean=a=>a.reduce((s,x)=>s+x,0)/(a.length||1);
function vectorOf(row){const v=row?.features?.vector||{};return FEATURES.map(k=>Number.isFinite(Number(v[k]))?Number(v[k]):0)}
function labelOf(x){return x==='ai'?1:x==='human'?0:null}
function stratified(rows){const ai=rows.filter(r=>labelOf(r.proposed_label)===1),hu=rows.filter(r=>labelOf(r.proposed_label)===0);const split=a=>{const ordered=[...a].sort((x,y)=>String(x.asset_sha256).localeCompare(String(y.asset_sha256)));const test=[],train=[];ordered.forEach((x,i)=>(i%5===0?test:train).push(x));if(!test.length&&train.length>1)test.push(train.pop());return{train,test}};const A=split(ai),H=split(hu);return{train:[...A.train,...H.train],test:[...A.test,...H.test],counts:{ai:ai.length,human:hu.length}}}
function stats(X){const mu=FEATURES.map((_,j)=>mean(X.map(r=>r[j]))),sd=FEATURES.map((_,j)=>Math.sqrt(mean(X.map(r=>(r[j]-mu[j])**2)))||1);return{mu,sd}}
function norm(v,s){return v.map((x,i)=>(x-s.mu[i])/s.sd[i])}
function predict(v,m){let z=m.bias;for(let i=0;i<m.weights.length;i++)z+=m.weights[i]*v[i];return sigmoid(z)}
function metrics(rows,model,s){let tp=0,tn=0,fp=0,fn=0;for(const r of rows){const y=labelOf(r.proposed_label),p=predict(norm(vectorOf(r),s),model)>=.5?1:0;if(y===1&&p===1)tp++;else if(y===0&&p===0)tn++;else if(y===0)fp++;else fn++}const safe=(a,b)=>b?a/b:0,precision=safe(tp,tp+fp),recall=safe(tp,tp+fn),specificity=safe(tn,tn+fp),accuracy=safe(tp+tn,tp+tn+fp+fn);return{n:tp+tn+fp+fn,tp,tn,fp,fn,accuracy:+accuracy.toFixed(4),precision:+precision.toFixed(4),recall:+recall.toFixed(4),specificity:+specificity.toFixed(4),f1:+safe(2*precision*recall,precision+recall).toFixed(4),balancedAccuracy:+((recall+specificity)/2).toFixed(4)}}
function train(rows,opts={}){const usable=rows.filter(r=>r.review_status==='approved'&&r.trust_tier>=2&&labelOf(r.proposed_label)!==null);const split=stratified(usable);if(split.counts.ai<10||split.counts.human<10){const e=new Error(`Need at least 10 approved high-trust AI and 10 human examples. Current: AI ${split.counts.ai}, human ${split.counts.human}.`);e.code='INSUFFICIENT_DATA';throw e}const X=split.train.map(vectorOf),s=stats(X),data=split.train.map(r=>({x:norm(vectorOf(r),s),y:labelOf(r.proposed_label)}));let weights=FEATURES.map(()=>0),bias=0;const lr=Number(opts.learningRate||.035),epochs=Math.max(500,Math.min(5000,Number(opts.epochs||1800))),l2=.003;for(let e=0;e<epochs;e++){const gw=weights.map(()=>0);let gb=0;for(const r of data){const p=predict(r.x,{weights,bias}),err=p-r.y;gb+=err;for(let j=0;j<weights.length;j++)gw[j]+=err*r.x[j]}for(let j=0;j<weights.length;j++)weights[j]-=lr*(gw[j]/data.length+l2*weights[j]);bias-=lr*gb/data.length}const model={family:'emet_local_multimodal_logistic',features:FEATURES,weights:weights.map(x=>+x.toFixed(8)),bias:+bias.toFixed(8),normalization:{mean:s.mu.map(x=>+x.toFixed(8)),sd:s.sd.map(x=>+x.toFixed(8))},threshold:.5};return{model,counts:split.counts,train:metrics(split.train,model,s),test:metrics(split.test,model,s),dataset:{total:usable.length,train:split.train.length,test:split.test.length},parameters:{epochs,learningRate:lr,l2,featureCount:FEATURES.length}}}
module.exports={FEATURES,train};