'use strict';
const Module=require('module');
const fs=require('fs');
const originalLoad=Module._load;
const clamp=n=>Math.max(0,Math.min(100,Math.round(Number(n)||0)));
const median=a=>{if(!a?.length)return 0;const s=[...a].sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2};
function absoluteCell(c){const ch=c?.channels||{};let s=12;const abs=Number(c.absoluteScore);if(Number.isFinite(abs))return clamp(abs);if(Number(ch.cfa)>=1.2)s+=18;if(Number(ch.channelResidual)>=1.2)s+=15;if(Number(ch.flatNoise)>=1.2)s+=13;if(Number(ch.jpegPhase)>=1.2)s+=12;if(Number(ch.edgeNoise)>=1.2)s+=12;if(Number(ch.laplacian)>=1.2)s+=8;if(Number(ch.noise)>=1.2)s+=7;return clamp(Math.max(s,Number(c.score)||0));}
function calibrate(result,existing){const loc=result?.localization,heat=loc?.heatmap,cells=heat?.cells;if(!Array.isArray(cells)||!cells.length)return result;for(const c of cells)c.absoluteScore=absoluteCell(c);const vals=cells.map(c=>c.absoluteScore),med=median(vals),high=cells.filter(c=>c.absoluteScore>=65).length/cells.length,o=result.aiOriginEstimate||{},camera=Number(o?.cameraEvidence?.score||0),generator=(existing?.metadata?.generatorFingerprints||[]).length>0,consensus=clamp(med*.72+high*100*.28),base=Number(o.score)||0;let score=clamp(base*.72+consensus*.28-camera*.04);if(generator)score=Math.max(score,98);o.score=score;o.absolutePatchConsensus=consensus;o.absolutePatchMedian=Math.round(med);o.absolutePatchHighCoverage=Math.round(high*1000)/1000;o.signals=Array.isArray(o.signals)?o.signals:[];if(!o.signals.some(x=>x.id==='absolute_patch_consensus'))o.signals.push({id:'absolute_patch_consensus',score:consensus,weight:.18,kind:'origin'});const whole=generator||(score>=78&&med>=55&&high>=.42)||(score>=88);loc.wholeImageEvidence={absolutePatchMedian:Math.round(med),absolutePatchHighCoverage:Math.round(high*1000)/1000,consensus};if(whole){loc.mode='whole_image';loc.coverage=Math.max(Number(loc.coverage)||0,Math.round(Math.max(.9,high)*1000)/1000);}result.version='EMET-VISION-FUSION-2026.09.15.2';return result;}
Module._load=function(request,parent,isMain){const exp=originalLoad.apply(this,arguments);if((request==='./advanced-image-forensics'||/advanced-image-forensics(?:\.js)?$/.test(request))&&exp?.analyzeAdvancedImage&&!exp.__emetPatched){const fn=exp.analyzeAdvancedImage;exp.analyzeAdvancedImage=async(buffer,existing={})=>calibrate(await fn(buffer,existing),existing);Object.defineProperty(exp,'__emetPatched',{value:true});}return exp;};
const originalRead=fs.readFileSync;
const browserPatch=`<script>(()=>{function color(s){s=+s||0;return s>=75?'rgba(230,74,59,.30)':s>=55?'rgba(243,154,43,.25)':s>=35?'rgba(243,210,59,.18)':'rgba(43,182,115,.07)'}async function paint(){const d=window.__EMET_MEDIA_LAST_SCAN,f=window.__EMET_MEDIA_FILE,c=document.querySelector('.emetImageCanvas');if(!d||!f||!c||c.dataset.heat2)return;const cells=d?.multimodal?.visionFusion?.localization?.heatmap?.cells||[];if(!cells.length)return;c.dataset.heat2='1';await new Promise(r=>setTimeout(r,120));const x=c.getContext('2d'),w=c.width,h=c.height,whole=d?.multimodal?.visionFusion?.localization?.mode==='whole_image',score=+d?.multimodal?.visionFusion?.aiOriginEstimate?.score||0;for(const q of cells){let s=+(q.absoluteScore??q.score??0);if(whole&&score>=70)s=Math.max(s,score*.82);x.fillStyle=color(s);x.fillRect(q.x*w,q.y*h,Math.ceil(q.w*w)+1,Math.ceil(q.h*h)+1)}if(whole&&score>=75){x.strokeStyle=score>=85?'rgba(190,32,32,.95)':'rgba(224,125,22,.95)';x.lineWidth=Math.max(3,w/220);x.strokeRect(2,2,w-4,h-4)}}new MutationObserver(()=>setTimeout(paint,160)).observe(document.documentElement,{childList:true,subtree:true});setTimeout(paint,300)})();</script>`;
fs.readFileSync=function(p,enc){const out=originalRead.apply(this,arguments);try{if(typeof out==='string'&&String(p).endsWith('verify.html')&&!out.includes('data-emet-heatmap-v2'))return out.replace('</body>',`<span data-emet-heatmap-v2 hidden></span>${browserPatch}</body>`);}catch{}return out;};
