'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {inspectText,assess,phraseHits,wordSpans}=require('../evidence-text');
const {parseXml,metadataFromXml,canonicalDocument,repairFilename}=require('../evidence-document');
const {interpretStore}=require('../provenance-reader');
const W='http://schemas.openxmlformats.org/wordprocessingml/2006/main';
const wrap=body=>`<w:document xmlns:w="${W}"><w:body>${body}</w:body></w:document>`;
test('Hebrew boundaries detect standalone transitions, not substrings',()=>{assert.equal(phraseHits('בנוסף גם לכן. לבנוסף אין התאמה',['בנוסף','לכן']).length,2)});
test('Niqqud remains in one token',()=>assert.equal(wordSpans('שָׁלוֹם').length,1));
test('Hebrew script is recognized',()=>assert.equal(inspectText('שלום וברכה').language.code,'he'));
test('CJK is not labelled Hebrew',()=>assert.equal(inspectText('这是一个测试').language.code,'zh'));
test('Empty content is undetermined, never human',()=>{const r=assess(inspectText(''));assert.equal(r.language.code,'und');assert.equal(r.ai.proven,false);assert.equal(r.ai.probability,null)});
test('Explicit first-person Hebrew AI use is a statement, not proof',()=>{const r=assess(inspectText('השתמשתי בבינה מלאכותית לניסוח הטקסט.'));assert.equal(r.ai.status,'self_reported');assert.equal(r.ai.proven,false)});
test('Denial is not an admission',()=>assert.equal(assess(inspectText('לא השתמשתי בבינה מלאכותית.')).ai.status,'not_assessed'));
test('A research discussion is not an admission',()=>assert.equal(assess(inspectText('לדוגמה: השתמשתי בבינה מלאכותית.')).ai.status,'not_assessed'));
test('Quoted statement is not an admission',()=>assert.equal(assess(inspectText('הוא כתב "I used AI" בתגובה.')).ai.status,'not_assessed'));
test('AI topic headings are not classified as AI',()=>assert.equal(assess(inspectText('מערכת לזיהוי בינה מלאכותית')).ai.status,'not_assessed'));
test('Disclosure section produces the exact quote',()=>{const r=inspectText('הצהרה על שימוש בכלי בינה מלאכותית\nהשימוש נעשה לשיפור ניסוח ועריכה לשונית.');assert.equal(r.findings[0].quote,'השימוש נעשה לשיפור ניסוח ועריכה לשונית.')});
test('Emoji and Hebrew locators round-trip in codepoints and UTF16',()=>{const s='🧪 שָׁלוֹם\nהשתמשתי בבינה מלאכותית.';const f=inspectText(s).findings[0],l=f.locator;assert.equal(Array.from(s).slice(l.startCodePoint,l.endCodePoint).join(''),f.quote);assert.equal(s.slice(l.startUTF16,l.endUTF16),f.quote)});
test('Long document tail is inspected, not silently truncated',()=>{const r=inspectText('טקסט רגיל.\n'.repeat(30000)+'השתמשתי בבינה מלאכותית.');assert.equal(r.findings.length,1);assert.equal(r.coverage.fraction,1);assert.equal(r.coverage.truncated,false)});
test('Ordinary boilerplate gets no probability',()=>assert.equal(assess(inspectText('לפיכך ולכן בנוסף חשוב לציין. '.repeat(30))).model.probabilityAI,null));
test('Assistant phrase is observed, not a full authorship claim',()=>assert.equal(assess(inspectText('As an AI language model, I can explain.')).ai.status,'content_signal'));
test('Adjacent Word runs are not separated into fake words',()=>{const r=canonicalDocument({'word/document.xml':wrap('<w:p><w:r><w:t>של</w:t></w:r><w:r><w:t>ום</w:t></w:r></w:p>')});assert.equal(r.text,'שלום')});
test('Deleted text is not analysed as visible authorship',()=>{const r=canonicalDocument({'word/document.xml':wrap('<w:p><w:del w:author="Someone"><w:r><w:delText>I used AI</w:delText></w:r></w:del><w:r><w:t>שלום</w:t></w:r></w:p>')});assert.equal(r.text,'שלום');assert.equal(r.revisions.length,1)});
test('Text in tables is preserved',()=>{const r=canonicalDocument({'word/document.xml':wrap('<w:tbl><w:tr><w:tc><w:p><w:r><w:t>נתונים</w:t></w:r></w:p></w:tc></w:tr></w:tbl>')});assert.equal(r.text,'נתונים')});
test('Hidden text is counted and excluded',()=>{const r=canonicalDocument({'word/document.xml':wrap('<w:p><w:r><w:rPr><w:vanish/></w:rPr><w:t>I used AI</w:t></w:r><w:r><w:t>שלום</w:t></w:r></w:p>')});assert.equal(r.text,'שלום');assert.equal(r.hiddenTextCount,1)});
test('Modified timestamp is not confused with lastModifiedBy',()=>{const r=metadataFromXml('<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:d="http://purl.org/dc/terms/"><cp:lastModifiedBy>1</cp:lastModifiedBy><d:modified>2026-09-09T20:45:00Z</d:modified></cp:coreProperties>');assert.equal(r.lastModifiedBy,'1');assert.equal(r.modified,'2026-09-09T20:45:00Z')});
test('DTD rejected without entity expansion',()=>assert.throws(()=>parseXml('<!DOCTYPE x [<!ENTITY a "bad">]><x>&a;</x>')));
test('Filename mojibake repairs without altering proper Hebrew',()=>{const s='שלום.docx';assert.equal(repairFilename(s),s);assert.equal(repairFilename(Buffer.from(s).toString('latin1')),s)});
const manifest=(state,actions=[],title='normal')=>({active_manifest:'m',validation_state:state,manifests:{m:{title,assertions:[{label:'c2pa.actions.v2',data:{actions}}]}}});
test('C2PA keyword in a title is not verified AI',()=>assert.equal(interpretStore(manifest('Trusted',[],'AI generated')).aiDeclared,false));
test('Valid and trusted are separate C2PA states',()=>{const r=interpretStore(manifest('Valid'));assert.equal(r.validationPassed,true);assert.equal(r.trusted,false)});
test('Invalid C2PA does not authenticate its AI declaration',()=>{const r=interpretStore(manifest('Invalid',[{digitalSourceType:'http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia'}]));assert.equal(r.aiDeclared,true);assert.equal(r.claimAuthenticated,false)});
test('Unknown validation never defaults to trusted',()=>assert.equal(interpretStore(manifest(undefined)).trusted,false));
test('Only the active manifest supplies current-source assertions',()=>{const r=manifest('Trusted');r.manifests.old={assertions:[{label:'c2pa.actions',data:{actions:[{digitalSourceType:'http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia'}]}}]};assert.equal(interpretStore(r).aiDeclared,false)});
test('Trusted active AI declaration is identified as an authenticated claim',()=>{const r=interpretStore(manifest('Trusted',[{digitalSourceType:'http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia'}]));assert.equal(r.aiDeclared,true);assert.equal(r.claimAuthenticated,true)});
